### ISSUE TITLE
Update the documentation for the end-user on the Navigator

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-docs#18]
The navigator is currently presented: 
- https://docs.wordlift.io/en/latest/discover.html?highlight=navigator#the-navigator-widget 
- https://docs.wordlift.io/en/latest/shortcodes.html?highlight=navigator#widget-shortcodes 

we need to update these parts with reference to the latest version.

**Comment by akshayraje** [comment]
In case of https://docs.wordlift.io/en/latest/discover.html?highlight=navigator#the-navigator-widget

I think we should modify the copy to reflect links to post (and optionally link to entity) as the new navigator primarily is designed to show post links and the default template only links to posts. The proposed copy here can be:

> Each tile presents a link to a related post. The template can be modified and styled as per the theme UI.

We should also change the screenshot to reflect the new navigator.

In case of https://docs.wordlift.io/en/latest/shortcodes.html?highlight=navigator#widget-shortcodes

We should also change the screenshot to reflect the new navigator and also add these following optional parameters:

> - **title**: (optional) Title to be displayed above navigator. Defaults to 'Related articles'
> - **limit**: (optional) The total number of posts to display. Defaults to 4
> - **template_id**: (optional) The id of the script element which has mustache template. For example if the template is in `<script id="wordlift_navigator_sidebar_template" type="text/mustache">...</script>` then template_id would be `wordlift_navigator_sidebar_template`
> - **post_id**: (optional) The post ID of a post of which navigator you want to display. Defaults to the current post. This is helpful if you want to display the navigator of post 'A' on post 'B' or add the navigator shortcode for a specific post in a non-post page.

Here's sample code for a typical template for reference:
```

<script id="wordlift_navigator_sidebar_template" type="text/mustache">
{{#items}}
<div class="related-articles__item">
  <a class="related-articles__img" href="{{post.permalink}}"><img src="{{{post.thumbnail}}}" alt="{{{post.title}}}" title="{{{post.title}}}"></a>
  <div class="related-articles__content">
    <h4 class="related-articles__title"><a href="{{post.permalink}}">{{{post.title}}}</a></h4>
  </div>
</div>
{{/items}}
</script>


```

**Comment by cyberandy** [comment]
All the updates here have been done, thanks for your help!
