### ISSUE TITLE
Create the documentation for personalizing the style of the new Navigator

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-docs#19]
We need to help theme developer personalize the look and feel of the Navigator by describing how to do it [here](https://docs.wordlift.io/en/latest/wordlift-theme-development.html)

**Comment by akshayraje** [comment]
By default the navigator would be wrapped in a `wl-navigator` class. The theme developer can style this and the child element classes using CSS.

Optionally, while using the navigator you also have an option of specifying a template_id of the script element which has mustache template.

Here's sample code for a typical template for reference:

```
<script id="wordlift_navigator_sidebar_template" type="text/mustache">
{{#items}}
<div class="related-articles__item">
  <a class="related-articles__img" href="{{post.permalink}}"><img src="{{{post.thumbnail}}}" alt="{{{post.title}}}" title="{{{post.title}}}"></a>
  <div class="related-articles__content">
    <h4 class="related-articles__title"><a href="{{post.permalink}}">{{{post.title}}}</a></h4>
  </div>
</div>
{{/items}}
</script>
```

In this case, the theme developer has complete flexibility over the contents of the template as well as the CSS styling of the same.

**Comment by cyberandy** [comment]
https://docs.wordlift.io/en/latest/wordlift-theme-development.html#personalization-of-the-navigator-widget
