### ISSUE TITLE
Create the documentation for the Context Cards

### ISSUE THREAD

**Issue by cyberandy** [insideout10/wordlift-docs#20]
This should describe to the end-user (editor) what it is and how it works. We also have to add a note to the theme developer to let them know how to disable it from the theme.

**Comment by akshayraje** [comment]
This can be a part of Links to Entity Pages section in the documentation here- https://docs.wordlift.io/en/latest/discover.html?highlight=navigator#links-to-entity-pages

The proposed copy that can be added here can be:

> By default context cards will show up on hovering if Links to Entity Pages are enabled for specific entities in your post. To disable context cards, add the following code to your theme: ```add_filter('wl_show_context_cards' '__return_false')```

A screenshot of context cards can also be added here.

**Comment by cyberandy** [comment]
https://docs.wordlift.io/en/latest/discover.html?highlight=navigator#context-cards
